### ISSUE TITLE
给个建议，加入银八指令太繁琐

### ISSUE THREAD

**Issue by 360add** [mrqx0195/nonebot_plugin_chikari_yinpa#11]
### 希望能解决的问题

加入银八指令太繁琐了，一般群友压根无法操作，导致没人玩这个，建议只发 ‘加入银趴’ 就可以以随机种族开启游戏，开启了以后后面一系列玩法就简单了

### 描述所需要的功能

‘加入银趴’指令可以直接开启游戏

**Comment by 360add** [comment]
![image](https://github.com/mrqx0195/nonebot_plugin_chikari_yinpa/assets/140232510/58d4b635-db32-45ff-8579-d8b4301b45c2)
hai'yo还有个建议，就是这个图上的种族不要显示数字，可以显示种族

**Comment by 360add** [comment]
银趴昵称最好是可以直接用当前群名称，比如输入加入银趴就自动用当前群名称加入并随机一个种族

**Comment by mrqx0195** [comment]
> 银趴昵称最好是可以直接用当前群名称，比如输入加入银趴就自动用当前群名称加入并随机一个种族

新版本已经整上了

**Comment by 360add** [comment]
更新了，感谢，希望插件越来越好

**Comment by 360add** [comment]
![image](https://github.com/mrqx0195/nonebot_plugin_chikari_yinpa/assets/140232510/e71101db-d21c-415c-a1c0-987879d1c145)
作者，更新后输入加入银趴报错了
