### ISSUE TITLE
Bug: 更新后输入加入银趴报错了

### ISSUE THREAD

**Issue by 360add** [mrqx0195/nonebot_plugin_chikari_yinpa#12]
### 操作系统

Windows

### Python 版本

11

### NoneBot 版本

2

### 适配器

11

### 协议端

1

### 描述问题

![image](https://github.com/mrqx0195/nonebot_plugin_chikari_yinpa/assets/140232510/d62927ab-09f3-4d3b-8498-c8e8c61b8642)
更新后输入 加入银趴 报错了

### 复现步骤

更新后输入 加入银趴 报错了

**Comment by 360add** [comment]
keyerror后面是机器人的q号

**Comment by mrqx0195** [comment]
已修
