### ISSUE TITLE
Bug: 大大更新后又出新的报错了

### ISSUE THREAD

**Issue by 360add** [mrqx0195/nonebot_plugin_chikari_yinpa#13]
### 操作系统

Windows

### Python 版本

11

### NoneBot 版本

2

### 适配器

2

### 协议端

1

### 描述问题

大大更新后输入 加入银趴 又出新的报错了。。。
![image](https://github.com/mrqx0195/nonebot_plugin_chikari_yinpa/assets/140232510/ebac9a84-780a-4fd5-8408-816ae68ec2ff)

### 复现步骤

新报错

**Comment by mrqx0195** [comment]
已修
